defaults:
  - dataset: re10k
  - optional dataset/view_sampler_dataset_specific_config: ${dataset/view_sampler}_${dataset} # todo dataset配置下应该有一个view_sampler字段
  - model/encoder: costvolume
  - model/decoder: splatting_cuda # todo 使用model/decoder/splatting_cuda.yaml -> cfg.model.decoder
  - loss: [mse]

wandb:
  # project: anysplat # todo project: 项目名字
  project: monosplat
  # entity: vvvsice
  entity: 1394945493-beijing-institute-of-technology # todo 项目归属用户或团队
  name: placeholder
  mode: online
  id: null

mode: train

dataset:
  overfit_to_scene: null # todo cfg.dataset覆盖或追加该字段

data_loader:
  # Avoid having to spin up new processes to print out visualizations.
  train:
    num_workers: 10
    persistent_workers: true
    batch_size: 4
    seed: 1234
  test:
    num_workers: 4
    persistent_workers: false
    batch_size: 1 # todo
    seed: 2345
  val:
    num_workers: 1
    persistent_workers: true
    batch_size: 1
    seed: 3456

optimizer:
  lr: 2.e-4
  warm_up_steps: 2000
  cosine_lr: true

checkpointing:
  load: null # todo test时，从此路径加载权重；train时，从此路径加载resume
  every_n_train_steps: 20000  # 5000
  save_top_k: -1
  pretrained_model: null # todo trian时，从此路径加载预训练模型权重
  pretrained_monodepth: null # todo train时，从此路径加载特征提取预训练权重
  resume: true # todo  当这个为true时，从pretrained_model加载

train:
  depth_mode: null
  extended_visualization: false
  print_log_every_n_steps: 1 #? 每隔多少次打印一次

test:
  output_path: outputs/test # todo test时，结果保存在此路径下
  compute_scores: false
  eval_time_skip_steps: 0
  save_image: true
  save_video: false

seed: 111123

trainer:
  max_steps: 1 #! 最大迭代次数，即迭代多少次后停止
  val_check_interval: 0.5 #! 0-1之间，如0.5 训练一半评估；大于1，整数，迭代多少此后评估
  gradient_clip_val: 0.5 #! 控制梯度大小
  # num_sanity_val_steps: 2 #! 正式训练之前跑几个验证batch检查数据流和模型是否正常
  num_sanity_val_steps: 0
  num_nodes: 1

output_dir: null
