defaults:
  - view_sampler: bounded

name: re10k # todo: re10k dataset的类(重要的)
roots: [datasets/re10k] # todo 数据集根目录，到train/test的上一级(重要的)
make_baseline_1: true
augment: true

image_shape: [180, 320]
background_color: [0.0, 0.0, 0.0]
cameras_are_circular: false

baseline_epsilon: 1e-3
max_fov: 100.0

skip_bad_shape: true
near: -1.
far: -1.
baseline_scale_bounds: true
shuffle_val: true
test_len: -1
test_chunk_interval: 1
test_times_per_scene: 1
